### ISSUE TITLE
[FEATURE] OPT-175B service authentication and new priority queue

### ISSUE THREAD

**Issue by zhisbug** [alpa-projects/alpa#700] opened 2022-09-13 17:12 UTC
## Background

Currently, the OPT serving backend does not have a good priority mechanism. It is (mostly) a first-come-first-serve queue.
The only priority rule is that the `completion` endpoint has a higher priority than the `logprob` endpoint.

We would like to implement the following new priority order (from high to low) in the [batching loop](https://github.com/alpa-projects/alpa/blob/5cd7f7dd6eddf687bff895543883c6a0388e8451/examples/llm_serving/launch_model_worker.py#L82).
  - 1st (interactive jobs): Requests from website users who pass the recaptcha test. These are low-frequent jobs.
  - 2nd (background jobs): Requests from client library users with API keys. To share a single backend among all users, we can use weighted round-robin or lottery scheduling. We can assign different weights to different API keys.
  - 3rd: Requests from users without API keys

With the new priority mechanism, we want to only assign priority according to the source of the requests and deprecate the old rule. `completion` endpoint and `logprob` endpoint will have the same priority.

## Useful pointers
- The existing priority queue https://github.com/alpa-projects/alpa/blob/5cd7f7dd6eddf687bff895543883c6a0388e8451/examples/llm_serving/launch_model_worker.py#L54
- How to distinguish interactive requests from the website and requests from the client library. Interactive requests from the website have Recaptcha information attached. Background requests from the client library have API keys attached.  https://github.com/alpa-projects/alpa/blob/5cd7f7dd6eddf687bff895543883c6a0388e8451/examples/llm_serving/launch_model_worker.py#L321-L331

**Comment by zhisbug** [comment] 2022-09-14 03:35
@aurickq

**Comment by JubilantJerry** [comment] 2023-01-10 17:21
@Weltberg and I are thinking about contributing this feature. There's several possibilities for how the weighting could be done, I wonder what you think would be the best for this project?

1. We could strictly pick high priority tasks over lower priority tasks all the time. As I understand it, the current code always prioritizes `completion` tasks whenever they exist, only running `logprob` tasks if no `completion` tasks are queued. Something similar could be done for the 3 priority classes introduced in the feature. But you mention weighted round robin and lottery scheduling, which still runs the lower priority tasks sometimes. I imagine this is a good thing since it avoids starvation, so I'm pretty sure you don't want strict priority scheduling. But I just wanted to clarify.

2. Let's say we go with weighted round robin, should we also use this scheduler to prioritize `completion` over `logprob`? I imagine that the current code only currently uses strict prioritization because it's simpler, and that this logic should be removed if there's a better scheduler. But changing this prioritization is indeed a change in existing behavior, and technically could be a regression for people using the `completion` endpoint. My opinion is that using the new scheduler for this is fine, since a regression can only happen if your servers are constantly near 100% utilization, which implies that there's already serious starvation problems for `logprob` today.

3. Should each API key have its own queue with its own priority (implemented in an efficient way to avoid constructing a lot of queue objects, of course), or do we bucket all requests into a fixed small number of priority buckets? It's a pretty significant difference in behavior. If there's 98 clients of weight 5, and 1 client of weight 10, all of which are constantly making requests, then in the first scheme the weight 10 client is allotted 2% of the server time, while in the second scheme he's allotted 67% of the server time. If higher priority requests are significantly more important than lower priority keys (e.g. if you want to keep the latency for the reCAPTCHA requests small even if it means they cut in front of a lot of API key requests), then I think the second scheme makes more sense. But that would make higher weighted API keys massively superior to lower weighted API keys, like one user with a higher weight API key is able to use most of the server resources no matter how many lower priority users exist. My opinion is that there should be two levels of scheduling, the first level having 3 queues for scheduling the reCAPTCHA user group vs. API key user group vs. other user group, and the second level having a lot of queues where users further divide the fraction of the server time allocated for the API key user group / other user group.

4. I'm thinking that the weight information should go inside `keys_file.json`, and that there's a default weight used for API keys not given an explicit weight. Would that work? (How do new API keys get added to `keys_file.json` anyway, does the server have to be brought down to make an update?)

**Comment by merrymercy** [comment] 2023-01-11 12:05
@JubilantJerry 
1. You are right. We want to avoid starvation.
2. No. With the new priority mechanism. We want to assign the same priority level to `logprob` and `completion`
3. Your two-level scheduling makes a lot of sense. Let's implement it.
4. Yes. We want to read the weights from `keys_file.json`

**Comment by merrymercy** [comment] 2023-01-27 19:03
Closed by #852

**Closed by merrymercy** 2023-01-27 19:03 UTC
Labels: enhancement, good first issue
